### ISSUE TITLE
cards de publicidade dos parceiros | add ads on partners

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas#106]
![image](https://user-images.githubusercontent.com/26682838/120946995-bed78200-c714-11eb-9fb1-d7a798fda519.png)
![codandodozero](https://user-images.githubusercontent.com/26682838/120947006-c6972680-c714-11eb-98d0-68429d03df17.jpg)
![larissa ](https://user-images.githubusercontent.com/26682838/120947017-cc8d0780-c714-11eb-9e19-24c100f4690b.jpeg)

inserir as duas imagens alinhadas com o botao indo para a api do whatsapp com os numeros  codando do zero - 54 9953-5187 and larissa classes  11 94283-6109
two images with button with api for whatsapp numbers codando do zero - 54 9953-5187 and larissa classes  11 94283-6109

**Comment by michelebarreto** [comment]
tarefa concluída.
