### ISSUE TITLE
alinhar botao cadastre no menu  | align "cadastre-se"button on header

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas#116]
![image](https://user-images.githubusercontent.com/26682838/121466836-79be8480-c98e-11eb-94e8-b165cb71764a.png)
![image](https://user-images.githubusercontent.com/26682838/121466858-817e2900-c98e-11eb-9c8c-f1548b95808b.png)

**Comment by michelebarreto** [comment]
verificar se está correto
