### ISSUE TITLE
change text color to white | trocar cor do texto para branco

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas#145]
:us:  this text area is wiped out, we need to change the color to white like we did on h2 - titles
:brazil:  esse texto do meio está meio apagado, precisa colocar ele em branco igual o titulo

![image](https://user-images.githubusercontent.com/26682838/132111323-ab64046a-b625-4dcf-82f8-79ca57e90de7.png)

**Comment by monteirocamis** [comment]
transform this text on white 
![image](https://user-images.githubusercontent.com/26682838/135737913-5c12e417-f78b-40d2-855d-bd93a053b3f9.png)

**Comment by jawariaalvi32** [comment]
Hey! Please assign me this.

**Comment by monteirocamis** [comment]
done =)

**Comment by jawariaalvi32** [comment]
Created a pull request. @monteirocamis please review.
