### ISSUE TITLE
remove "tráfego - análises de dados" | remover o " tráfego - análises de dados"  

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas#154]
![image](https://user-images.githubusercontent.com/26682838/135370978-76e8fe91-fc96-4ab9-aaf6-dded4a08f3c1.png)
****

**Comment by AB-Jeet** [comment]
Can you pls assign it to me .

**Comment by monteirocamis** [comment]
yes @AB-Jeet  =) thank you for your help !
