### ISSUE TITLE
refactor: style file adjustments | ajustes no arquivo de estilo

### ISSUE THREAD

**Issue by edilsonalves** [Codivas/landing-codivas#183]
🇺🇸 Currently, the file responsible for styling the page (`assets/css/style.css`), has several duplicate code snippets. It would be ideal to carry out a sanitization, which would positively impact the readability and organization of the file.

🇧🇷 Atualmente, o arquivo responsável pela estilização da página (`assets/css/style.css`), encontra-se com vários trechos de código duplicados. Seria ideal realizar uma sanitização, o que impactaria positivamente na legibilidade e organização do arquivo.

**Comment by monteirocamis** [comment]
Thank you @edilsonalves 
may be  in some moment we made more than one style archive ?

**Comment by edilsonalves** [comment]
> Thank you @edilsonalves may be in some moment we made more than one style archive ?

@monteirocamis, apparently it was just an accidental copy and paste that caused the problem.

**Comment by edilsonalves** [comment]
> Is this assigned to someone? Thank you

Hi, @merikettapearl212! The issue was not attributed to anyone... Feel free if you can contribute.
Thanks!

**Comment by monteirocamis** [comment]
> Hi so sorry I’ve had some family emergency come up. Please feel free to assign this to someone else thank you

Heey @merikettapearl212  come back this year :)

**Comment by tabita-barbosa** [comment]
Hello Camis! Can I take this issue? 
do I have to create a fork or can I sent the PR from a clone of the repository?

**Comment by monteirocamis** [comment]
Hi Tabita, yes please !! =)

**Comment by monteirocamis** [comment]
@tabita-barbosa  Do you want me to insert this task for you?

**Comment by tabita-barbosa** [comment]
yes, please!
i already did a pr fixing this issue.

**Comment by tabita-barbosa** [comment]
Yes, please! @monteirocamis 
here is the PR with the issue solved
https://github.com/Codivas/landing-codivas/pull/209
