### ISSUE TITLE
🟢 multi language button to English version 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas#205]
Hello hello!
please help us to include a button on top to switch for English version

**Comment by bea3853** [comment]
Oi @monteirocamis, faz sentido o que estou fazendo, é mais ou menos isso?
  acha que ficaria legal aqui?
![image](https://user-images.githubusercontent.com/55098795/193743446-cb1a5007-22fd-4b34-96dd-4fb6ac35b078.png)

**Comment by bea3853** [comment]
@monteirocamis  caso exista uma wireframe me dá um toque.

**Comment by bea3853** [comment]
OU prefere a barra do Google mesmo?
![image](https://user-images.githubusercontent.com/55098795/193746667-3db550fc-4f78-468c-b2f5-b207ca770f37.png)

**Comment by monteirocamis** [comment]
parece otimo @bea3853  !! 🥰👏
esse do google traduz pra qualquer lingua assim? 🥹
de prioridade era mais o ingles mas se tiver mais manda ver hehe

assim que tiver incluido so mandar o pull request 

⚠️obs: não esqueça de fazer seu registro no site do hacktoberfest para participar e receber seus brindes

**Comment by bea3853** [comment]
é uma API do google que faz a tradução, bem simples de utilizar. Obrigada fiz o registro.  ainda hoje já envio o pull.
