### ISSUE TITLE
create tab button to change language to English 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas#207]

**Comment by monteirocamis** [comment]
@bea3853 oi amore, o legal é mostrar e ai a pessoa muda de idioma e as divs mudam pra idiomas correspondente sabe ?

**Comment by bea3853** [comment]
Olá @monteirocamis, a função já está pronta. vou ver se consigo ao menos subir as alterações, até terça feira.

**Comment by bea3853** [comment]
Olá @monteirocamis, depois me diz se fez sentido para você.

**Comment by monteirocamis** [comment]
tudo certo !

**Comment by monteirocamis** [comment]
perfeito @bea3853  !!!
Só falta terminar as outras seções, é isso ?

**Comment by bea3853** [comment]
Bom dia Camis, isso mesmo. Podemos fazer uma força tarefa. A função está bem simples. 
Mas vou continuar inserindo novas traduções as divs.

**Comment by monteirocamis** [comment]
pode ser xuxu!!
 ou do lado do menu sanduíche sera? 
 uma coisa que tava pensando .. e se a pessoa falar ingles mas nao for dos sua? hahaha so tem bandeira dos sua ne
