### ISSUE TITLE
include blog link on nav header  |  incluir blog  no header -nav

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas#91]
:us:  we have our blog on www.blog.codivas.com.br and need  to include in our nav menu  as a "blog" link item

:brazil:  nós temos um blog que está em blog.codivas.com.br, precisamos incluir no menu

![image](https://user-images.githubusercontent.com/26682838/135766692-bce11160-c943-4ca2-a5cc-c92055f4f299.png)

**Comment by alepeglow** [comment]
tipo o nome igual do portfolio e quando clicar ir para o blog?

**Comment by monteirocamis** [comment]
isso mesmo le :) pode ser ali do lado do portfolio ate haha

**Comment by alepeglow** [comment]
Coloca pra mim então

**Comment by monteirocamis** [comment]
@alepeglow uma pessoa já incluiu, você pode agora so mudar pra do laado de contato ao inves de deixar ele como primeiro ? =)

**Comment by monteirocamis** [comment]
hey girls! @michelebarreto included the link for us, but now it is better if we put the "blog" on the right side of the "contato" }
Somebody could repositionize the item please?

**Comment by alepeglow** [comment]
posso fazer sim ..  só dar o pull aqui.
ao lado de contato ou de portifolio é melhor?

**Comment by PiligalC0D3** [comment]
❤
